--CREATE DATABASE STORAGE_SYSTEM;

--USE STORAGE_SYSTEM;

CREATE TABLE SYS_PHONE(
 PHONE_ID INT PRIMARY KEY
,PHONE_NUMBER INT
,PHONE_STATUS BIT
);

CREATE TABLE SYS_MAIL(
 MAIL_ID INT PRIMARY KEY
,MAIL VARCHAR(300)
,MAIL_STATUS BIT
);

CREATE TABLE SYS_ADDRESS(
 ADDRESS_ID INT PRIMARY KEY
,USER_ADDRESS VARCHAR(1000)
,ADDRESS_STATUS BIT
);

CREATE TABLE SYS_PRODUCT(
 PRODUCT_ID INT PRIMARY KEY
,PRODUCT_NAME VARCHAR(50)
,PRODUCT_DESCRIPCION VARCHAR(1000)
,PRODUCT_PRICE DECIMAL(12,2)
,CUANTITY INT
,PRODUCT_STATUS BIT
);

CREATE TABLE SYS_USER(
 ID_USER INT PRIMARY KEY
,USERNAME VARCHAR(50)
,LASTNAME VARCHAR(50)
,USER_ROLE VARCHAR(45)
,USER_STATUS BIT
,PHONE_ID_SYS_PHONE INT --REFERENCES FROM SYS_PHONE
,MAIL_ID_SYS_MAIL INT --REFERENCES FROM SYS_MAIL
,ADDRESS_ID_SYS_ADDRESS INT --REFERENCES FROM SYS_ADDRESS
,FOREIGN KEY (PHONE_ID_SYS_PHONE) REFERENCES SYS_PHONE(PHONE_ID)
,FOREIGN KEY (MAIL_ID_SYS_MAIL) REFERENCES SYS_MAIL(MAIL_ID)
,FOREIGN KEY (ADDRESS_ID_SYS_ADDRESS) REFERENCES SYS_ADDRESS(ADDRESS_ID)
);

CREATE TABLE SYS_HISTORY(
 ID_HISTORY INT PRIMARY KEY
,ACTIVITY VARCHAR(50) -- WHAT DID THE USER INSERT OR STRACT PRODUCTS FROM THE INVENTORY
,DATE_MODIFIED DATETIME
,USER_ID_SYS_USER INT
,PRODUCT_ID_SYS_PRODUCT INT --REFERENCES FROM SYS_PRODUCT
,ID_USER_SYS_USER INT --REFERENCES FROM SYS_USER
,FOREIGN KEY (PRODUCT_ID_SYS_PRODUCT) REFERENCES SYS_PRODUCT(PRODUCT_ID)
,FOREIGN KEY (ID_USER_SYS_USER) REFERENCES SYS_USER(ID_USER)
);

CREATE TABLE SYS_PASSWORD(
 ID_PASSWORD INT PRIMARY KEY
,USER_PASSWORD VARCHAR(12)
,DAY_CREATION DATE
,DAY_MODIFIED DATE
,PASSWORD_STATUS BIT
,USER_ID_SYS_USER INT --REFERENCES FROM SYS_USER
,FOREIGN KEY (USER_ID_SYS_USER) REFERENCES SYS_USER(ID_USER)
);

